language: node_js

services:
  - mongodb

before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

script: 
  - cd backend
  - npm install
  - npm test

notifications:
  slack:
    rooms:
      - 4350bestgroup:m06K9lBnOM8qbXKJsg5qsWkN#general
    on_success: change # default: always
    on_failure: always # default: always